---
- name: "extract backend files"
  become: true
  shell: |
    pwd && ls
    # mkdir -p /home/ubuntu/backend
    tar xfC ~/project/artifact.tar.gz /home/ubuntu

- name: "start the app"
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start