---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install node and npm"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: Install "pm2" node.js package globally.
  npm:
    name: pm2
    global: yes
    
- name: "extract backend files"
  become: true
  shell: |
    pwd
    ls
    cd /home/ubuntu
    tar xf artifact.tar.gz

- name: "start the app"
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start