---
- name: Copy artifact.tar.gz file to EC2 Instance
  become: true
  ansible.builtin.copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: Unarchive artifact.tar.gz file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: "start the app"
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start

